### ISSUE TITLE
Unable to use get_budgets function with new flexible budgets feature in Monarch enabled

### ISSUE THREAD

**Issue by mpluscakes** [hammem/monarchmoney#119]
Since converting to use the flexible budgets option in Monarch, now getting the following error when trying to pull budget data:

```
Traceback (most recent call last):
  File "/Users/matt/dev/monarch.py", line 114, in <module>
    main()
  File "/Users/matt/dev/monarch.py", line 43, in main
    budgets = asyncio.run(mm.get_budgets(start_date="2024-10-01",end_date="2024-10-31"))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/matt/Library/Python/3.9/lib/python/site-packages/monarchmoney/monarchmoney.py", line 1338, in get_budgets
    return await self.gql_call(
  File "/Users/matt/Library/Python/3.9/lib/python/site-packages/monarchmoney/monarchmoney.py", line 2765, in gql_call
    return await self._get_graphql_client().execute_async(
  File "/Users/matt/Library/Python/3.9/lib/python/site-packages/gql/client.py", line 367, in execute_async
    return await session.execute(
  File "/Users/matt/Library/Python/3.9/lib/python/site-packages/gql/client.py", line 1639, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'Something went wrong while processing: None on request_id: None.', 'locations': [{'line': 120, 'column': 5}]}
```

**Comment by b3nw** [comment]
@hammem still running into this issue, when will v0.1.16 be released and incorporate this fix?
